import openai from './config.js';
import { openai, supabase } from './config.js';
import podcasts from './content.js';

/** Create embeddings representing the input text */
// async function main() {
//   const embedding = await openai.embeddings.create({
//     model: "text-embedding-ada-002",
//     input: "The quick brown fox jumped over the lazy dog",
//   });
//   console.log(embedding);
// }

// main();





// async function main(input) {
//   await Promise.all(
//     input.map( async(textChunk) => {
//         const embeddingResponse = await openai.embeddings.create({
//             model: "text-embedding-ada-002",
//             input: textChunk,
//         });
//         const data = { content: textChunk, embedding: embeddingResponse.data[0].embedding }
//         console.log(data);  
//     })    
//   );
//   console.log('Embedding complete!');
// }
// main(content);



// Store vector embeddings
// async function main(input) {
//   const data = await Promise.all(
//     input.map( async (textChunk) => {
//         const embeddingResponse = await openai.embeddings.create({
//             model: "text-embedding-ada-002",
//             input: textChunk
//         });
//         return { 
//           content: textChunk, 
//           embedding: embeddingResponse.data[0].embedding 
//         }
//     })
//   );
  
//   // Insert content and embedding into Supabase
//   await supabase.from('documents').insert(data); 
//   console.log('Embedding and storing complete!');
// }

// main(podcasts)


// Similarity search

// User query about podcasts
const query = "Jammin' in the Big Easy";
main(query);

/*
  Create an embedding from the user input and return a 
  semantically matching text chunk from the database 
*/
async function main(input) {
  // Create a vector embedding representing the input text
  const embeddingResponse = await openai.embeddings.create({
    model: "text-embedding-ada-002",
    input,
  }); 
  
  // The vector generated by OpenAI
  const embedding = embeddingResponse.data[0].embedding;
  
  // Query Supabase for nearest vector match
  const { data } = await supabase.rpc('match_documents', {
    query_embedding: embedding,
    match_threshold: 0.50,
    match_count: 1
  });
  console.log(data[0].content, data[0].similarity);
}

